[package]
name = "binary-rs"
version = "0.0.1"
authors = ["Mathias Danielsen <mathiasda98@hotmail.com>"]
edition = "2018"

description = "A binary reader/writer library for rust"
repository = "https://github.com/mathias234/binary-rs"
readme = "README.md"
keywords = ["binary", "reader", "writer"]
license = "MIT"

[dependencies]
bincode = "1.0.1"